import type { Country } from './types';

export const COUNTRIES: Country[] = [
  { name: 'Afghanistan', code: '+93', iso: 'AF', phoneLength: 9 },
  { name: 'Albania', code: '+355', iso: 'AL', phoneLength: 9 },
  { name: 'Algeria', code: '+213', iso: 'DZ', phoneLength: 9 },
  { name: 'American Samoa', code: '+1-684', iso: 'AS', phoneLength: 10 },
  { name: 'Andorra', code: '+376', iso: 'AD', phoneLength: 6 },
  { name: 'Angola', code: '+244', iso: 'AO', phoneLength: 9 },
  { name: 'Anguilla', code: '+1-264', iso: 'AI', phoneLength: 10 },
  { name: 'Antarctica', code: '+672', iso: 'AQ', phoneLength: 6 },
  { name: 'Antigua and Barbuda', code: '+1-268', iso: 'AG', phoneLength: 10 },
  { name: 'Argentina', code: '+54', iso: 'AR', phoneLength: [6, 8] },
  { name: 'Armenia', code: '+374', iso: 'AM', phoneLength: 8 },
  { name: 'Aruba', code: '+297', iso: 'AW', phoneLength: 7 },
  { name: 'Australia', code: '+61', iso: 'AU', phoneLength: 9 },
  { name: 'Austria', code: '+43', iso: 'AT', phoneLength: [10, 13] },
  { name: 'Azerbaijan', code: '+994', iso: 'AZ', phoneLength: 9 },
  { name: 'Bahamas', code: '+1-242', iso: 'BS', phoneLength: 10 },
  { name: 'Bahrain', code: '+973', iso: 'BH', phoneLength: 8 },
  { name: 'Bangladesh', code: '+880', iso: 'BD', phoneLength: 10 },
  { name: 'Barbados', code: '+1-246', iso: 'BB', phoneLength: 10 },
  { name: 'Belarus', code: '+375', iso: 'BY', phoneLength: 9 },
  { name: 'Belgium', code: '+32', iso: 'BE', phoneLength: 9 },
  { name: 'Belize', code: '+501', iso: 'BZ', phoneLength: 7 },
  { name: 'Benin', code: '+229', iso: 'BJ', phoneLength: 8 },
  { name: 'Bermuda', code: '+1-441', iso: 'BM', phoneLength: 10 },
  { name: 'Bhutan', code: '+975', iso: 'BT', phoneLength: 8 },
  { name: 'Bolivia', code: '+591', iso: 'BO', phoneLength: 8 },
  { name: 'Bosnia and Herzegovina', code: '+387', iso: 'BA', phoneLength: 8 },
  { name: 'Botswana', code: '+267', iso: 'BW', phoneLength: 7 },
  { name: 'Brazil', code: '+55', iso: 'BR', phoneLength: [10, 11] },
  { name: 'British Indian Ocean Territory', code: '+246', iso: 'IO', phoneLength: 7 },
  { name: 'British Virgin Islands', code: '+1-284', iso: 'VG', phoneLength: 10 },
  { name: 'Brunei', code: '+673', iso: 'BN', phoneLength: 7 },
  { name: 'Bulgaria', code: '+359', iso: 'BG', phoneLength: 9 },
  { name: 'Burkina Faso', code: '+226', iso: 'BF', phoneLength: 8 },
  { name: 'Burundi', code: '+257', iso: 'BI', phoneLength: 8 },
  { name: 'Cambodia', code: '+855', iso: 'KH', phoneLength: [8, 9] },
  { name: 'Cameroon', code: '+237', iso: 'CM', phoneLength: 9 },
  { name: 'Canada', code: '+1', iso: 'CA', phoneLength: 10 },
  { name: 'Cape Verde', code: '+238', iso: 'CV', phoneLength: 7 },
  { name: 'Cayman Islands', code: '+1-345', iso: 'KY', phoneLength: 10 },
  { name: 'Central African Republic', code: '+236', iso: 'CF', phoneLength: 8 },
  { name: 'Chad', code: '+235', iso: 'TD', phoneLength: 8 },
  { name: 'Chile', code: '+56', iso: 'CL', phoneLength: 9 },
  { name: 'China', code: '+86', iso: 'CN', phoneLength: 11 },
  { name: 'Christmas Island', code: '+61', iso: 'CX', phoneLength: 9 },
  { name: 'Cocos Islands', code: '+61', iso: 'CC', phoneLength: 9 },
  { name: 'Colombia', code: '+57', iso: 'CO', phoneLength: 10 },
  { name: 'Comoros', code: '+269', iso: 'KM', phoneLength: 7 },
  { name: 'Cook Islands', code: '+682', iso: 'CK', phoneLength: 5 },
  { name: 'Costa Rica', code: '+506', iso: 'CR', phoneLength: 8 },
  { name: 'Croatia', code: '+385', iso: 'HR', phoneLength: [8, 9] },
  { name: 'Cuba', code: '+53', iso: 'CU', phoneLength: 8 },
  { name: 'Curacao', code: '+599', iso: 'CW', phoneLength: 7 },
  { name: 'Cyprus', code: '+357', iso: 'CY', phoneLength: 8 },
  { name: 'Czech Republic', code: '+420', iso: 'CZ', phoneLength: 9 },
  { name: 'Democratic Republic of the Congo', code: '+243', iso: 'CD', phoneLength: 9 },
  { name: 'Denmark', code: '+45', iso: 'DK', phoneLength: 8 },
  { name: 'Djibouti', code: '+253', iso: 'DJ', phoneLength: 6 },
  { name: 'Dominica', code: '+1-767', iso: 'DM', phoneLength: 10 },
  { name: 'Dominican Republic', code: '+1-809', iso: 'DO', phoneLength: 10 },
  { name: 'East Timor', code: '+670', iso: 'TL', phoneLength: [7, 8] },
  { name: 'Ecuador', code: '+593', iso: 'EC', phoneLength: 9 },
  { name: 'Egypt', code: '+20', iso: 'EG', phoneLength: 10 },
  { name: 'El Salvador', code: '+503', iso: 'SV', phoneLength: 8 },
  { name: 'Equatorial Guinea', code: '+240', iso: 'GQ', phoneLength: 9 },
  { name: 'Eritrea', code: '+291', iso: 'ER', phoneLength: 7 },
  { name: 'Estonia', code: '+372', iso: 'EE', phoneLength: [7, 8] },
  { name: 'Ethiopia', code: '+251', iso: 'ET', phoneLength: 9 },
  { name: 'Falkland Islands', code: '+500', iso: 'FK', phoneLength: 5 },
  { name: 'Faroe Islands', code: '+298', iso: 'FO', phoneLength: 6 },
  { name: 'Fiji', code: '+679', iso: 'FJ', phoneLength: 7 },
  { name: 'Finland', code: '+358', iso: 'FI', phoneLength: [9, 11] },
  { name: 'France', code: '+33', iso: 'FR', phoneLength: 9 },
  { name: 'French Polynesia', code: '+689', iso: 'PF', phoneLength: 8 },
  { name: 'Gabon', code: '+241', iso: 'GA', phoneLength: [7, 8] },
  { name: 'Gambia', code: '+220', iso: 'GM', phoneLength: 7 },
  { name: 'Georgia', code: '+995', iso: 'GE', phoneLength: 9 },
  { name: 'Germany', code: '+49', iso: 'DE', phoneLength: [10, 11] },
  { name: 'Ghana', code: '+233', iso: 'GH', phoneLength: 9 },
  { name: 'Gibraltar', code: '+350', iso: 'GI', phoneLength: 8 },
  { name: 'Greece', code: '+30', iso: 'GR', phoneLength: 10 },
  { name: 'Greenland', code: '+299', iso: 'GL', phoneLength: 6 },
  { name: 'Grenada', code: '+1-473', iso: 'GD', phoneLength: 10 },
  { name: 'Guam', code: '+1-671', iso: 'GU', phoneLength: 10 },
  { name: 'Guatemala', code: '+502', iso: 'GT', phoneLength: 8 },
  { name: 'Guernsey', code: '+44-1481', iso: 'GG', phoneLength: 10 },
  { name: 'Guinea', code: '+224', iso: 'GN', phoneLength: 9 },
  { name: 'Guinea-Bissau', code: '+245', iso: 'GW', phoneLength: 7 },
  { name: 'Guyana', code: '+592', iso: 'GY', phoneLength: 7 },
  { name: 'Haiti', code: '+509', iso: 'HT', phoneLength: 8 },
  { name: 'Honduras', code: '+504', iso: 'HN', phoneLength: 8 },
  { name: 'Hong Kong', code: '+852', iso: 'HK', phoneLength: 8 },
  { name: 'Hungary', code: '+36', iso: 'HU', phoneLength: 9 },
  { name: 'Iceland', code: '+354', iso: 'IS', phoneLength: 7 },
  { name: 'India', code: '+91', iso: 'IN', phoneLength: 10 },
  { name: 'Indonesia', code: '+62', iso: 'ID', phoneLength: [10, 12] },
  { name: 'Iran', code: '+98', iso: 'IR', phoneLength: 10 },
  { name: 'Iraq', code: '+964', iso: 'IQ', phoneLength: 10 },
  { name: 'Ireland', code: '+353', iso: 'IE', phoneLength: 9 },
  { name: 'Isle of Man', code: '+44-1624', iso: 'IM', phoneLength: 10 },
  { name: 'Israel', code: '+972', iso: 'IL', phoneLength: 9 },
  { name: 'Italy', code: '+39', iso: 'IT', phoneLength: [9, 11] },
  { name: 'Ivory Coast', code: '+225', iso: 'CI', phoneLength: 8 },
  { name: 'Jamaica', code: '+1-876', iso: 'JM', phoneLength: 10 },
  { name: 'Japan', code: '+81', iso: 'JP', phoneLength: 10 },
  { name: 'Jersey', code: '+44-1534', iso: 'JE', phoneLength: 10 },
  { name: 'Jordan', code: '+962', iso: 'JO', phoneLength: 9 },
  { name: 'Kazakhstan', code: '+7', iso: 'KZ', phoneLength: 10 },
  { name: 'Kenya', code: '+254', iso: 'KE', phoneLength: 9 },
  { name: 'Kiribati', code: '+686', iso: 'KI', phoneLength: 5 },
  { name: 'Kosovo', code: '+383', iso: 'XK', phoneLength: 8 },
  { name: 'Kuwait', code: '+965', iso: 'KW', phoneLength: 8 },
  { name: 'Kyrgyzstan', code: '+996', iso: 'KG', phoneLength: 9 },
  { name: 'Laos', code: '+856', iso: 'LA', phoneLength: [8, 9] },
  { name: 'Latvia', code: '+371', iso: 'LV', phoneLength: 8 },
  { name: 'Lebanon', code: '+961', iso: 'LB', phoneLength: [7, 8] },
  { name: 'Lesotho', code: '+266', iso: 'LS', phoneLength: 8 },
  { name: 'Liberia', code: '+231', iso: 'LR', phoneLength: [7, 8] },
  { name: 'Libya', code: '+218', iso: 'LY', phoneLength: 9 },
  { name: 'Liechtenstein', code: '+423', iso: 'LI', phoneLength: 7 },
  { name: 'Lithuania', code: '+370', iso: 'LT', phoneLength: 8 },
  { name: 'Luxembourg', code: '+352', iso: 'LU', phoneLength: 9 },
  { name: 'Macau', code: '+853', iso: 'MO', phoneLength: 8 },
  { name: 'Macedonia', code: '+389', iso: 'MK', phoneLength: 8 },
  { name: 'Madagascar', code: '+261', iso: 'MG', phoneLength: 9 },
  { name: 'Malawi', code: '+265', iso: 'MW', phoneLength: [7, 9] },
  { name: 'Malaysia', code: '+60', iso: 'MY', phoneLength: [9, 10] },
  { name: 'Maldives', code: '+960', iso: 'MV', phoneLength: 7 },
  { name: 'Mali', code: '+223', iso: 'ML', phoneLength: 8 },
  { name: 'Malta', code: '+356', iso: 'MT', phoneLength: 8 },
  { name: 'Marshall Islands', code: '+692', iso: 'MH', phoneLength: 7 },
  { name: 'Mauritania', code: '+222', iso: 'MR', phoneLength: 8 },
  { name: 'Mauritius', code: '+230', iso: 'MU', phoneLength: 8 },
  { name: 'Mayotte', code: '+262', iso: 'YT', phoneLength: 9 },
  { name: 'Mexico', code: '+52', iso: 'MX', phoneLength: 10 },
  { name: 'Micronesia', code: '+691', iso: 'FM', phoneLength: 7 },
  { name: 'Moldova', code: '+373', iso: 'MD', phoneLength: 8 },
  { name: 'Monaco', code: '+377', iso: 'MC', phoneLength: [8, 9] },
  { name: 'Mongolia', code: '+976', iso: 'MN', phoneLength: 8 },
  { name: 'Montenegro', code: '+382', iso: 'ME', phoneLength: 8 },
  { name: 'Montserrat', code: '+1-664', iso: 'MS', phoneLength: 10 },
  { name: 'Morocco', code: '+212', iso: 'MA', phoneLength: 9 },
  { name: 'Mozambique', code: '+258', iso: 'MZ', phoneLength: 9 },
  { name: 'Myanmar', code: '+95', iso: 'MM', phoneLength: [8, 9] },
  { name: 'Namibia', code: '+264', iso: 'NA', phoneLength: [7, 9] },
  { name: 'Nauru', code: '+674', iso: 'NR', phoneLength: 7 },
  { name: 'Nepal', code: '+977', iso: 'NP', phoneLength: 10 },
  { name: 'Netherlands', code: '+31', iso: 'NL', phoneLength: 9 },
  { name: 'Netherlands Antilles', code: '+599', iso: 'AN', phoneLength: [7, 8] },
  { name: 'New Caledonia', code: '+687', iso: 'NC', phoneLength: 6 },
  { name: 'New Zealand', code: '+64', iso: 'NZ', phoneLength: [8, 10] },
  { name: 'Nicaragua', code: '+505', iso: 'NI', phoneLength: 8 },
  { name: 'Niger', code: '+227', iso: 'NE', phoneLength: 8 },
  { name: 'Nigeria', code: '+234', iso: 'NG', phoneLength: [7, 10] },
  { name: 'Niue', code: '+683', iso: 'NU', phoneLength: 4 },
  { name: 'North Korea', code: '+850', iso: 'KP', phoneLength: [4, 10] },
  { name: 'Northern Mariana Islands', code: '+1-670', iso: 'MP', phoneLength: 10 },
  { name: 'Norway', code: '+47', iso: 'NO', phoneLength: 8 },
  { name: 'Oman', code: '+968', iso: 'OM', phoneLength: 8 },
  { name: 'Pakistan', code: '+92', iso: 'PK', phoneLength: 10 },
  { name: 'Palau', code: '+680', iso: 'PW', phoneLength: 7 },
  { name: 'Palestine', code: '+970', iso: 'PS', phoneLength: 9 },
  { name: 'Panama', code: '+507', iso: 'PA', phoneLength: [7, 8] },
  { name: 'Papua New Guinea', code: '+675', iso: 'PG', phoneLength: 8 },
  { name: 'Paraguay', code: '+595', iso: 'PY', phoneLength: 9 },
  { name: 'Peru', code: '+51', iso: 'PE', phoneLength: 9 },
  { name: 'Philippines', code: '+63', iso: 'PH', phoneLength: 10 },
  { name: 'Pitcairn', code: '+64', iso: 'PN', phoneLength: 9 },
  { name: 'Poland', code: '+48', iso: 'PL', phoneLength: 9 },
  { name: 'Portugal', code: '+351', iso: 'PT', phoneLength: 9 },
  { name: 'Puerto Rico', code: '+1-787', iso: 'PR', phoneLength: 10 },
  { name: 'Qatar', code: '+974', iso: 'QA', phoneLength: 8 },
  { name: 'Republic of the Congo', code: '+242', iso: 'CG', phoneLength: 9 },
  { name: 'Reunion', code: '+262', iso: 'RE', phoneLength: 9 },
  { name: 'Romania', code: '+40', iso: 'RO', phoneLength: 9 },
  { name: 'Russia', code: '+7', iso: 'RU', phoneLength: 10 },
  { name: 'Rwanda', code: '+250', iso: 'RW', phoneLength: 9 },
  { name: 'Saint Barthelemy', code: '+590', iso: 'BL', phoneLength: 9 },
  { name: 'Saint Helena', code: '+290', iso: 'SH', phoneLength: 4 },
  { name: 'Saint Kitts and Nevis', code: '+1-869', iso: 'KN', phoneLength: 10 },
  { name: 'Saint Lucia', code: '+1-758', iso: 'LC', phoneLength: 10 },
  { name: 'Saint Martin', code: '+590', iso: 'MF', phoneLength: 9 },
  { name: 'Saint Pierre and Miquelon', code: '+508', iso: 'PM', phoneLength: 6 },
  { name: 'Saint Vincent and the Grenadines', code: '+1-784', iso: 'VC', phoneLength: 10 },
  { name: 'Samoa', code: '+685', iso: 'WS', phoneLength: [5, 7] },
  { name: 'San Marino', code: '+378', iso: 'SM', phoneLength: [6, 10] },
  { name: 'Sao Tome and Principe', code: '+239', iso: 'ST', phoneLength: 7 },
  { name: 'Saudi Arabia', code: '+966', iso: 'SA', phoneLength: 9 },
  { name: 'Senegal', code: '+221', iso: 'SN', phoneLength: 9 },
  { name: 'Serbia', code: '+381', iso: 'RS', phoneLength: [8, 9] },
  { name: 'Seychelles', code: '+248', iso: 'SC', phoneLength: 7 },
  { name: 'Sierra Leone', code: '+232', iso: 'SL', phoneLength: 8 },
  { name: 'Singapore', code: '+65', iso: 'SG', phoneLength: 8 },
  { name: 'Sint Maarten', code: '+1-721', iso: 'SX', phoneLength: 10 },
  { name: 'Slovakia', code: '+421', iso: 'SK', phoneLength: 9 },
  { name: 'Slovenia', code: '+386', iso: 'SI', phoneLength: 8 },
  { name: 'Solomon Islands', code: '+677', iso: 'SB', phoneLength: 7 },
  { name: 'Somalia', code: '+252', iso: 'SO', phoneLength: [8, 9] },
  { name: 'South Africa', code: '+27', iso: 'ZA', phoneLength: 9 },
  { name: 'South Korea', code: '+82', iso: 'KR', phoneLength: [9, 10] },
  { name: 'South Sudan', code: '+211', iso: 'SS', phoneLength: 9 },
  { name: 'Spain', code: '+34', iso: 'ES', phoneLength: 9 },
  { name: 'Sri Lanka', code: '+94', iso: 'LK', phoneLength: 9 },
  { name: 'Sudan', code: '+249', iso: 'SD', phoneLength: 9 },
  { name: 'Suriname', code: '+597', iso: 'SR', phoneLength: [6, 7] },
  { name: 'Svalbard and Jan Mayen', code: '+47', iso: 'SJ', phoneLength: 8 },
  { name: 'Swaziland', code: '+268', iso: 'SZ', phoneLength: 8 },
  { name: 'Sweden', code: '+46', iso: 'SE', phoneLength: [7, 9] },
  { name: 'Switzerland', code: '+41', iso: 'CH', phoneLength: 9 },
  { name: 'Syria', code: '+963', iso: 'SY', phoneLength: 9 },
  { name: 'Taiwan', code: '+886', iso: 'TW', phoneLength: 9 },
  { name: 'Tajikistan', code: '+992', iso: 'TJ', phoneLength: 9 },
  { name: 'Tanzania', code: '+255', iso: 'TZ', phoneLength: 9 },
  { name: 'Thailand', code: '+66', iso: 'TH', phoneLength: 9 },
  { name: 'Togo', code: '+228', iso: 'TG', phoneLength: 8 },
  { name: 'Tokelau', code: '+690', iso: 'TK', phoneLength: 4 },
  { name: 'Tonga', code: '+676', iso: 'TO', phoneLength: 5 },
  { name: 'Trinidad and Tobago', code: '+1-868', iso: 'TT', phoneLength: 10 },
  { name: 'Tunisia', code: '+216', iso: 'TN', phoneLength: 8 },
  { name: 'Turkey', code: '+90', iso: 'TR', phoneLength: 10 },
  { name: 'Turkmenistan', code: '+993', iso: 'TM', phoneLength: 8 },
  { name: 'Turks and Caicos Islands', code: '+1-649', iso: 'TC', phoneLength: 10 },
  { name: 'Tuvalu', code: '+688', iso: 'TV', phoneLength: [5, 6] },
  { name: 'U.S. Virgin Islands', code: '+1-340', iso: 'VI', phoneLength: 10 },
  { name: 'Uganda', code: '+256', iso: 'UG', phoneLength: 9 },
  { name: 'Ukraine', code: '+380', iso: 'UA', phoneLength: 9 },
  { name: 'United Arab Emirates', code: '+971', iso: 'AE', phoneLength: 9 },
  { name: 'United Kingdom', code: '+44', iso: 'GB', phoneLength: 10 },
  { name: 'United States', code: '+1', iso: 'US', phoneLength: 10 },
  { name: 'Uruguay', code: '+598', iso: 'UY', phoneLength: 8 },
  { name: 'Uzbekistan', code: '+998', iso: 'UZ', phoneLength: 9 },
  { name: 'Vanuatu', code: '+678', iso: 'VU', phoneLength: [5, 7] },
  { name: 'Vatican', code: '+379', iso: 'VA', phoneLength: 10 },
  { name: 'Venezuela', code: '+58', iso: 'VE', phoneLength: 10 },
  { name: 'Vietnam', code: '+84', iso: 'VN', phoneLength: 9 },
  { name: 'Wallis and Futuna', code: '+681', iso: 'WF', phoneLength: 6 },
  { name: 'Western Sahara', code: '+212', iso: 'EH', phoneLength: 9 },
  { name: 'Yemen', code: '+967', iso: 'YE', phoneLength: 9 },
  { name: 'Zambia', code: '+260', iso: 'ZM', phoneLength: 9 },
  { name: 'Zimbabwe', code: '+263', iso: 'ZW', phoneLength: 9 },
];